volumes:
  pg-admin:
    external: true
  wander-list-data:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      SIGNING_KEY: ${REACT_APP_SIGNING_KEY}
      ALGORITHM: "HS256"
      DATABASE_URL: postgresql://cookie_monsters:postgres@db/wander_list
      WAIT_HOSTS: db:5432
      NPS_KEY: ${REACT_APP_NPS_KEY}
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_ALERT_HOST: ${REACT_APP_ALERT_HOST}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_NPS_KEY: ${REACT_APP_NPS_KEY}

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: cookiemonsters@wanderlist.com
      PGADMIN_DEFAULT_PASSWORD: nationalparks
      PGADMIN_DISABLE_POSTFIX: 1
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: cookie_monsters
      POSTGRES_DB: wander_list
    ports:
      - "15432:5432"
    volumes:
      - wander-list-data:/var/lib/postgresql/data
